name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Force xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    # - name: Resolve dependencies
    #   run: |
    #     xcodebuild -resolvePackageDependencies

    - name: Run tests
      run: |
        xcodebuild test -workspace ModuleExamples.xcworkspace -scheme 'ModuleExamples' -destination 'name=iPhone 8'

    - name: Compile project
      run: |
        xcodebuild clean build -workspace ModuleExamples.xcworkspace -scheme 'ModuleExamples' -destination 'name=iPhone 8'