name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v2

    # Github Actions' machines do in fact have recent versions of Xcode,
    # but you may have to explicitly switch to them.  We explicitly want
    # to use Xcode 12, so we use xcode-select to switch to it.
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app

    - name: Run tests
      run: |
        xcodebuild test -workspace ModuleExamples.xcworkspace -scheme ModuleExamples -destination 'name=iPhone 11'

    - name: Compile project (in Release)
      run: |
        xcodebuild build -workspace ModuleExamples.xcworkspace -scheme ModuleExamples -destination 'name=iPhone 11'
